spring:
  application:
    name: BusTicketApp
  datasource:
    url: jdbc:postgresql://localhost:5432/busticket
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
stripe:
  secret-key: sk_test_51TLQD3GBfe54RqwiWorNLpbEyD0OQYDYF2Fsr0bJvBymfNdfu19Swq01YI7No8BXyWItRYSJxsH5nBA80nMmZFWZ00BZdTC1Hi
  publishable-key: pk_test_51TLQD3GBfe54Rqwiy9h8fXeqfCuKtraCuak6QVQl2sZQ1rjof3ThSiLgaLtVrpLQr1n9fFyDatsO8rXxcumSfPLC00KCkPK8ds
springdoc:
  swagger-ui:
    url: /openapi.yaml
jwt:
  secret: 35a66503a668ae49294e5401c05ab76fc31928111d92308325323f40f161ffce99
  audience: bus-ticket-app
  issuer: bus-ticket-app