spring:
  application:
    name: BusTicketApp
  datasource:
    url: jdbc:postgresql://localhost:5432/busticket
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
stripe:
  secret-key: ${STRIPE_SECRET_KEY}
  publishable-key: ${STRIPE_PUBLISHABLE_KEY}

springdoc:
  swagger-ui:
    url: /openapi.yaml
jwt:
  secret: ${JWT_SECRET}
  audience: ${JWT_AUDIENCE}
  issuer: ${JWT_ISSUER}
